"""
Convert toolpath waypoints to robot-executable commands.

Supports two output formats:
1. G-code (CNC/bioprinter style) -- ported from your MATLAB G-code generator
2. ROS 2 trajectory messages (for future integration)

Ported from your ExtractingGCodeFromWoundSegment.m with added extrusion control.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from numpy.typing import NDArray


def toolpath_to_gcode(
    waypoints: NDArray[np.float64],
    is_deposition: NDArray[np.bool_] | None = None,
    safe_z_mm: float = 5.0,
    work_z_mm: float = 0.5,
    feed_rate: float = 1500.0,
    extrusion_rate: float | None = None,
    layer_height_mm: float = 0.4,
    nozzle_diameter_mm: float = 0.41,
    output_path: str | Path | None = None,
) -> list[str]:
    """Convert waypoints to G-code for bioprinter execution.

    Parameters
    ----------
    waypoints : (N, 3) XYZ positions in mm
    is_deposition : (N,) bool mask. True = depositing, False = travel.
                    If None, all points are deposition.
    safe_z_mm : Z height for rapid travel moves
    work_z_mm : Z height for deposition (relative to surface)
    feed_rate : movement speed in mm/min
    extrusion_rate : if set, adds E commands for material extrusion
    layer_height_mm : for extrusion volume calculation
    nozzle_diameter_mm : for extrusion volume calculation
    output_path : if set, write G-code to file
    """
    if is_deposition is None:
        is_deposition = np.ones(len(waypoints), dtype=bool)

    lines = [
        "; Generated by LiveMesh",
        "; Real-time geometric toolpath for in-situ bioprinting",
        "G21 ; mm units",
        "G90 ; absolute positioning",
        f"G1 F{feed_rate:.0f}",
        f"G0 Z{safe_z_mm:.2f} ; safe height",
    ]

    e_total = 0.0
    prev_depositing = False

    for i, (pt, depositing) in enumerate(zip(waypoints, is_deposition)):
        x, y, z = pt

        if depositing and not prev_depositing:
            lines.append(f"G0 X{x:.3f} Y{y:.3f} ; rapid to start")
            lines.append(f"G1 Z{work_z_mm:.2f} ; lower to work height")
        elif not depositing and prev_depositing:
            lines.append(f"G0 Z{safe_z_mm:.2f} ; lift")

        if depositing:
            cmd = f"G1 X{x:.3f} Y{y:.3f}"
            if extrusion_rate is not None and i > 0:
                dist = np.linalg.norm(waypoints[i] - waypoints[i - 1])
                cross_section = layer_height_mm * nozzle_diameter_mm
                e_total += dist * cross_section * extrusion_rate
                cmd += f" E{e_total:.4f}"
            lines.append(cmd)
        elif not depositing and prev_depositing:
            lines.append(f"G0 X{x:.3f} Y{y:.3f} ; travel")

        prev_depositing = bool(depositing)

    lines.extend([
        f"G0 Z{safe_z_mm:.2f} ; final lift",
        "G0 X0 Y0 ; home",
        "M2 ; program end",
    ])

    if output_path is not None:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text("\n".join(lines))

    return lines


def toolpath_to_ros2_trajectory(
    waypoints: NDArray[np.float64],
    normals: NDArray[np.float64],
    tool_frames: NDArray[np.float64],
    velocity_mm_s: float = 25.0,
) -> list[dict]:
    """Convert toolpath to a list of pose dicts for ROS 2 trajectory execution.

    Each dict contains position (mm), orientation (quaternion), and timestamp.
    """
    trajectory = []
    t = 0.0

    for i in range(len(waypoints)):
        if i > 0:
            dist = np.linalg.norm(waypoints[i] - waypoints[i - 1])
            t += dist / velocity_mm_s

        quat = _rotation_to_quaternion(tool_frames[i])

        trajectory.append({
            "time_s": t,
            "position_mm": waypoints[i].tolist(),
            "orientation_quat": quat.tolist(),  # [x, y, z, w]
        })

    return trajectory


def _rotation_to_quaternion(R: NDArray[np.float64]) -> NDArray[np.float64]:
    """Convert 3x3 rotation matrix to quaternion [x, y, z, w]."""
    trace = np.trace(R)
    if trace > 0:
        s = 0.5 / np.sqrt(trace + 1.0)
        w = 0.25 / s
        x = (R[2, 1] - R[1, 2]) * s
        y = (R[0, 2] - R[2, 0]) * s
        z = (R[1, 0] - R[0, 1]) * s
    elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
        s = 2.0 * np.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
        w = (R[2, 1] - R[1, 2]) / s
        x = 0.25 * s
        y = (R[0, 1] + R[1, 0]) / s
        z = (R[0, 2] + R[2, 0]) / s
    elif R[1, 1] > R[2, 2]:
        s = 2.0 * np.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
        w = (R[0, 2] - R[2, 0]) / s
        x = (R[0, 1] + R[1, 0]) / s
        y = 0.25 * s
        z = (R[1, 2] + R[2, 1]) / s
    else:
        s = 2.0 * np.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
        w = (R[1, 0] - R[0, 1]) / s
        x = (R[0, 2] + R[2, 0]) / s
        y = (R[1, 2] + R[2, 1]) / s
        z = 0.25 * s

    return np.array([x, y, z, w])
